### ISSUE TITLE
Add the ability to delete biomes in the UI

### ISSUE THREAD

**Issue by BenOvermyer** [ironarachne/datacore#15]
On the biome index page, add a "Delete" button next to each biome's tag list. On clicking the button, a dialog will pop up confirming that the user wants to delete the biome. If they accept, then delete the biome from the database and return the user to the biome index page.

The HTTP action for this operation should use the `destroy` method in the `BiomeController`.

**Comment by chandresh1339** [comment]
Can I work on this request to create my first PR?

**Comment by BenOvermyer** [comment]
Yes, go ahead.

Cheers,
Ben

**Comment by chandresh1339** [comment]
Please check the changes done.
