### ISSUE TITLE
Add the ability to delete charges in the UI

### ISSUE THREAD

**Issue by BenOvermyer** [ironarachne/datacore#16]
On the charge index page, add a "Delete" button next to each charge. On clicking the button, a dialog will pop up confirming that the user wants to delete the charge. If they accept, then delete the charge from the database and return the user to the charge index page.

The HTTP action for this operation should use the destroy method in the ChargeController.

**Comment by glennforrest** [comment]
Taking a look at this

**Comment by JunaidJaved248** [comment]
@BenOvermyer Please check my PR, I have just fixed the  Issue!!
Review my code !!
Thanks
